sudo: required
services:
  - docker

before_install:
  - docker build -t gehtmaguad/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run gehtmaguad/react-test npm test -- --coverage

after_success:
  # Build images
  - docker build -t gehtmaguad/multi-client ./client
  - docker build -t gehtmaguad/multi-nginx ./nginx
  - docker build -t gehtmaguad/multi-server ./server
  - docker build -t gehtmaguad/multi-worker ./worker
  # Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images
  - docker push gehtmaguad/multi-client
  - docker push gehtmaguad/multi-nginx
  - docker push gehtmaguad/multi-server
  - docker push gehtmaguad/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker
  bucket_name: elasticbeanstalk-eu-central-1-143100638017
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY